In [2]:
import numpy as np
import yt
import matplotlib.pyplot as plt

In [3]:
ds = yt.load("/ptmp/mpa/bseidl/Simulation-Runs/2023-06-13_multiCloud_Series3-4_64clouds/data/id0/cloud.0042.vtk")#, parameters = [periodicity = (False,False,False)])

yt : [INFO     ] 2023-06-22 15:25:25,271 Temporarily setting domain_right_edge = -domain_left_edge. This will be corrected automatically if it is not the case.


yt : [WARNING  ] 2023-06-22 15:25:25,516 Assuming 1.0 = 1.0 cm
yt : [WARNING  ] 2023-06-22 15:25:25,518 Assuming 1.0 = 1.0 s
yt : [WARNING  ] 2023-06-22 15:25:25,518 Assuming 1.0 = 1.0 g
yt : [INFO     ] 2023-06-22 15:25:25,593 Parameters: current_time              = 42.00505
yt : [INFO     ] 2023-06-22 15:25:25,593 Parameters: domain_dimensions         = [640 640 640]
yt : [INFO     ] 2023-06-22 15:25:25,594 Parameters: domain_left_edge          = [-200. -200. -200.]
yt : [INFO     ] 2023-06-22 15:25:25,595 Parameters: domain_right_edge         = [200. 200. 200.]
yt : [INFO     ] 2023-06-22 15:25:25,596 Parameters: cosmological_simulation   = 0


In [4]:
dd = ds.all_data()
reg = ds.r[0.1:0.5, 0.3:0.7,0.3:0.7]

coveringgrid = ds.arbitrary_grid([-50,-50,-50], [150,100,100], dims=[320,240,240])

In [52]:
print(coveringgrid["gas","density"][:,:,:])
print(np.shape(coveringgrid["gas","density"][:,:,:]))

[[[1.0610224  1.06081271 1.06062269 ... 1.0607065  1.06124151 1.06181014]
  [1.06055319 1.06033671 1.06013513 ... 1.06050348 1.06103325 1.06159735]
  [1.0601033  1.05987394 1.0596509  ... 1.06030583 1.06083226 1.0613929 ]
  ...
  [1.07070875 1.0704999  1.07030845 ... 1.07106352 1.07062364 1.07026052]
  [1.07073379 1.07052982 1.07034349 ... 1.07056642 1.07017529 1.06985116]
  [1.0708164  1.07061636 1.07043767 ... 1.07010198 1.06975389 1.06948054]]

 [[1.05908108 1.05881774 1.05857325 ... 1.0593493  1.05986428 1.0604074 ]
  [1.05856276 1.05830598 1.05806744 ... 1.05915034 1.0596602  1.06019926]
  [1.05807018 1.05781758 1.05757868 ... 1.05895567 1.05946219 1.0599978 ]
  ...
  [1.06980288 1.06959653 1.06941211 ... 1.0712285  1.07069838 1.07026482]
  [1.06978369 1.0695802  1.06939685 ... 1.07071209 1.07023215 1.06984699]
  [1.06982219 1.06961858 1.06943345 ... 1.07020652 1.06978941 1.06944978]]

 [[1.05719316 1.05693388 1.05668485 ... 1.05800271 1.0584985  1.05901814]
  [1.05669451 1.056444

In [19]:
print(reg)

YTRegion (cloud.0042): , center=[0.3 0.5 0.5] cm, left_edge=[0.1 0.3 0.3] cm, right_edge=[0.5 0.7 0.7] cm


In [13]:
print(dd["gas",'density'])

[1.         1.         1.         ... 1.43092394 1.42613506 1.40976667] g/cm**3


In [5]:
#meandd = np.mean(dd["gas",'density'])
#meanreg = np.mean(reg["gas",'density'])
meancov = np.mean(coveringgrid["gas",'density'])



In [6]:
print(meancov)

1.5006790108383574 g/cm**3


In [ ]:
print(reg["gas","density"])
print(meandd, meanreg,meancov)


[0.94865549] g/cm**3
1.0240579334889695 g/cm**3 0.9486554861068726 g/cm**3


In [12]:
print("(x,  y,  z) Temperature")
for i in range(dd["gas", "temperature"].size):
    print(
        "(%f,  %f,  %f)    %f"
        % (
            dd["gas", "x"][i],
            dd["gas", "y"][i],
            dd["gas", "z"][i],
            dd["gas", "temperature"][i],
        )
    )

(x,  y,  z) Temperature
